# Generated by Django 4.2.7 on 2023-12-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=20)),
                ("asunto", models.CharField(max_length=100)),
                ("fecha", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "tabla_comentarios",
            },
        ),
    ]
