# Generated by Django 4.2.7 on 2023-12-03 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comentarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comentario",
            table="comentarios_db",
        ),
    ]
