# Generated by Django 4.2.7 on 2023-12-05 02:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_comment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="subjetc",
            new_name="subject",
        ),
    ]
